clustering/urls.py
from django.urls import path
from . import views

app_name = 'clustering'

urlpatterns = [
    path('', views.cluster, name='cluster')
]

interface/urls.py
from django.urls import path
from . import views

app_name = 'interfaces'

urlpatterns = [
    path('', views.list, name='list'),
    path('<int:trial_id>/', views.results, name='results')
]

nycrime/urls.py
from django.urls import path, include
from django.contrib import admin


from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('interface.urls')),
    path('clustering/', include('clustering.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clustering/models.py
from django.db import models

# Create your models here.

interface/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Trial(models.Model):
    pd_cd = models.FloatField()
    law_cat_cd = models.FloatField()
    s_sex = models.FloatField()
    s_age = models.FloatField()
    s_race = models.FloatField()
    v_sex = models.FloatField()
    v_age = models.FloatField()
    v_race = models.FloatField()
    image = models.ImageField()

    def __str__(self):
        return str(self.pk)

clustering/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

# Clustering (templates/interfaces/index.html)
def cluster(request):
    return HttpResponse(request.POST['PD_CD'])

interface/views.py
from django.shortcuts import render
from .models import Trial

def list(request):
    trials = Trial.objects.all()
    context = { 'trials': trials}
    return render(request, 'interfaces/index.html', context)

def results(request, trial_id):
    trial = Trial.objects.get(pk=trial_id)
    context = { 'trial': trial }  
    return render(request, 'interfaces/result.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>NY Crime Data Clustering</title>
  </head>
  <body>
    <!-- NavBar -->
    {% include 'partials/_navbar.html' %}
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/interfaces/index.html
{% extends 'base.html' %}
{% block content%}
    <div class="container">
        <div class="row">
            <div class="col-8">
                    <h1 class="text-center mb-3">Lists</h1>
                    {% if trials %}
                        {% for trial in trials %}
                        <div class="card mb-3">
                            <div class="card-body">
                                <h5 class="card-title">Case {{ trial.pk }}</h5>
                                <p class="text-right">PD_CD: {{ trial.pd_cd }}</p>
                                <p class="text-right">LAW_CAT_CD: {{ trial.law_cat_cd }}</p>
                                <p class="text-right"></p>
                                <p class="text-right"></p>
                                <p class="text-right"></p>
                                <p class="text-right"></p>
                                <p class="text-right"></p>
                                <p class="text-right"></p>
                                <a href="{% url 'interfaces:results' trial_id=trial.id %}" class="btn btn-primary btn-sm">Results</a>
                            </div>
                        </div>
                        {% endfor %}
                    {% else %}
                        <p>No clusters</p>
                    {% endif %}
            </div>
            <div class="col-4">
                <h1 class="text-center mb-3">Clustering</h1>
                <form action="{% url 'clustering:cluster' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-check mb-4">
                        <label for="PD_CD">PD_CD</label>
                        <input type="text" id="PD_CD" name="PD_CD" required />
                    </div> 
                    <input type="submit" value="Submit" class="btn btn-success btn-lg">
                </form>
            </div>
        </div>
    </div>
    
{% endblock %}

templates/interfaces/result.html
{% extends 'base.html' %}
{% block content%}
<div class="container">
        <div class="row">
          <div class="col-md-12 m-auto">
                <img src="/media/{{trial.image }}" class="img-fluid" alt="Responsive image">
          </div>
        </div>
      </div>
{% endblock %}

templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
    <div class="container">
        <a class="navbar-brand" href="/">Crime Data Clustering</a>
    </div>
</nav>